export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const SIGNUP_REQUEST = "LOGIN_REQUEST";
export const SIGNUP_SUCCESS = "LOGIN_SUCCESS";
export const SIGNUP_FAILURE = "LOGIN_FAILURE";

export const GETALLUSERS_REQUEST = "GETALLUSERS_REQUEST";
export const GETALLUSERS_SUCCESS = "GETALLUSERS_SUCCESS";
export const GETALLUSERS_FAILURE = "GETALLUSERS_FAILURE";
